// File generated by FlutterFire CLI — do not edit manually.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH8ihdmrtLoqJPZSqJeUxvSQkHaisaaMc',
    appId: '1:139253644280:web:1a54ee71a7074a9c8fb40d',
    messagingSenderId: '139253644280',
    projectId: 'ishbor-e94bf',
    authDomain: 'ishbor-e94bf.firebaseapp.com',
    storageBucket: 'ishbor-e94bf.firebasestorage.app',
    measurementId: 'G-D06C7S6K5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGuX1E0XVA1taoCJBJbB6WG6TTQBQ5FqQ',
    appId: '1:139253644280:android:16e7db446f9990358fb40d',
    messagingSenderId: '139253644280',
    projectId: 'ishbor-e94bf',
    storageBucket: 'ishbor-e94bf.firebasestorage.app',
  );
}
