import 'package:flutter/material.dart';

/// All supported job category slugs (matches L10n keys).
const List<String> kCategories = [
  'cat_it',
  'cat_driver',
  'cat_cook',
  'cat_waiter',
  'cat_designer',
  'cat_teacher',
  'cat_doctor',
  'cat_nurse',
  'cat_pharmacist',
  'cat_construction',
  'cat_sales',
  'cat_cashier',
  'cat_cleaner',
  'cat_security',
  'cat_accountant',
  'cat_marketing',
  'cat_engineer',
  'cat_electric',
  'cat_mechanic',
  'cat_tailor',
  'cat_farming',
  'cat_loader',
  'cat_warehouse',
  'cat_barber',
  'cat_beautician',
  'cat_baker',
  'cat_lawyer',
  'cat_translator',
  'cat_photographer',
  'cat_nanny',
  'cat_courier',
  'cat_plumber',
  'cat_welder',
  'cat_painter',
  'cat_gardener',
  'cat_hotel',
  'cat_fitness',
  'cat_real_estate',
  'cat_veterinary',
  'cat_receptionist',
  'cat_social_worker',
  'cat_psychologist',
  'cat_journalist',
  'cat_actor',
  'cat_musician',
  'cat_animator',
  'cat_event',
  'cat_cleaning_pro',
  'cat_glazier',
  'cat_tiler',
  'cat_roofer',
  'cat_carpenter',
  'cat_locksmith',
  'cat_laundry',
  'cat_carwash',
  'cat_tutor',
  'cat_admin',
  'cat_logistics',
  'cat_call_center',
  'cat_other',
];

/// Category → Material icon mapping.
const Map<String, IconData> kCategoryIcons = {
  'cat_it': Icons.computer_rounded,
  'cat_driver': Icons.directions_car_rounded,
  'cat_cook': Icons.restaurant_rounded,
  'cat_waiter': Icons.room_service_rounded,
  'cat_designer': Icons.design_services_rounded,
  'cat_teacher': Icons.school_rounded,
  'cat_doctor': Icons.local_hospital_rounded,
  'cat_nurse': Icons.medical_services_rounded,
  'cat_pharmacist': Icons.local_pharmacy_rounded,
  'cat_construction': Icons.construction_rounded,
  'cat_sales': Icons.storefront_rounded,
  'cat_cashier': Icons.point_of_sale_rounded,
  'cat_cleaner': Icons.cleaning_services_rounded,
  'cat_security': Icons.security_rounded,
  'cat_accountant': Icons.calculate_rounded,
  'cat_marketing': Icons.campaign_rounded,
  'cat_engineer': Icons.engineering_rounded,
  'cat_electric': Icons.bolt_rounded,
  'cat_mechanic': Icons.build_rounded,
  'cat_tailor': Icons.checkroom_rounded,
  'cat_farming': Icons.agriculture_rounded,
  'cat_loader': Icons.inventory_2_rounded,
  'cat_warehouse': Icons.warehouse_rounded,
  'cat_barber': Icons.content_cut_rounded,
  'cat_beautician': Icons.face_retouching_natural_rounded,
  'cat_baker': Icons.bakery_dining_rounded,
  'cat_lawyer': Icons.gavel_rounded,
  'cat_translator': Icons.translate_rounded,
  'cat_photographer': Icons.camera_alt_rounded,
  'cat_nanny': Icons.child_care_rounded,
  'cat_courier': Icons.delivery_dining_rounded,
  'cat_plumber': Icons.plumbing_rounded,
  'cat_welder': Icons.hardware_rounded,
  'cat_painter': Icons.format_paint_rounded,
  'cat_gardener': Icons.yard_rounded,
  'cat_hotel': Icons.hotel_rounded,
  'cat_fitness': Icons.fitness_center_rounded,
  'cat_real_estate': Icons.real_estate_agent_rounded,
  'cat_veterinary': Icons.pets_rounded,
  'cat_receptionist': Icons.support_agent_rounded,
  'cat_social_worker': Icons.volunteer_activism_rounded,
  'cat_psychologist': Icons.psychology_rounded,
  'cat_journalist': Icons.newspaper_rounded,
  'cat_actor': Icons.theater_comedy_rounded,
  'cat_musician': Icons.music_note_rounded,
  'cat_animator': Icons.animation_rounded,
  'cat_event': Icons.celebration_rounded,
  'cat_cleaning_pro': Icons.cleaning_services_rounded,
  'cat_glazier': Icons.window_rounded,
  'cat_tiler': Icons.grid_view_rounded,
  'cat_roofer': Icons.roofing_rounded,
  'cat_carpenter': Icons.handyman_rounded,
  'cat_locksmith': Icons.lock_rounded,
  'cat_laundry': Icons.local_laundry_service_rounded,
  'cat_carwash': Icons.local_car_wash_rounded,
  'cat_tutor': Icons.menu_book_rounded,
  'cat_admin': Icons.admin_panel_settings_rounded,
  'cat_logistics': Icons.local_shipping_rounded,
  'cat_call_center': Icons.headset_mic_rounded,
  'cat_other': Icons.more_horiz_rounded,
};

/// All Uzbekistan regions (slug → used as L10n key).
const List<String> kRegions = [
  'reg_tashkent_city',
  'reg_tashkent',
  'reg_samarkand',
  'reg_fergana',
  'reg_andijan',
  'reg_namangan',
  'reg_bukhara',
  'reg_khorezm',
  'reg_kashkadarya',
  'reg_surkhandarya',
  'reg_syrdarya',
  'reg_jizzakh',
  'reg_navoi',
  'reg_karakalpakstan',
];

/// Category → accent colour mapping (for card left-border + icon bg).
const Map<String, Color> kCategoryColors = {
  'cat_it': Color(0xFF2563EB),
  'cat_driver': Color(0xFF0EA5E9),
  'cat_cook': Color(0xFFF97316),
  'cat_waiter': Color(0xFFE8800A),
  'cat_designer': Color(0xFF8B5CF6),
  'cat_teacher': Color(0xFF10B981),
  'cat_doctor': Color(0xFFEF4444),
  'cat_nurse': Color(0xFFFF6B6B),
  'cat_pharmacist': Color(0xFF22C55E),
  'cat_construction': Color(0xFFF59E0B),
  'cat_sales': Color(0xFF06B6D4),
  'cat_cashier': Color(0xFF0891B2),
  'cat_cleaner': Color(0xFF64748B),
  'cat_security': Color(0xFF1D4ED8),
  'cat_accountant': Color(0xFF059669),
  'cat_marketing': Color(0xFFEC4899),
  'cat_engineer': Color(0xFF7C3AED),
  'cat_electric': Color(0xFFEAB308),
  'cat_mechanic': Color(0xFF6B7280),
  'cat_tailor': Color(0xFFDB2777),
  'cat_farming': Color(0xFF16A34A),
  'cat_loader': Color(0xFF92400E),
  'cat_warehouse': Color(0xFF78350F),
  'cat_barber': Color(0xFF0F766E),
  'cat_beautician': Color(0xFFBE185D),
  'cat_baker': Color(0xFFD97706),
  'cat_lawyer': Color(0xFF1E3A5F),
  'cat_translator': Color(0xFF4338CA),
  'cat_photographer': Color(0xFF7E22CE),
  'cat_nanny': Color(0xFFFF8FAB),
  'cat_courier': Color(0xFF2DD4BF),
  'cat_plumber': Color(0xFF0284C7),
  'cat_welder': Color(0xFF57534E),
  'cat_painter': Color(0xFFF4845F),
  'cat_gardener': Color(0xFF4ADE80),
  'cat_hotel': Color(0xFFF59E0B),
  'cat_fitness': Color(0xFFEF4444),
  'cat_real_estate': Color(0xFF0D9488),
  'cat_veterinary': Color(0xFF84CC16),
  'cat_receptionist': Color(0xFF06B6D4),
  'cat_social_worker': Color(0xFF0EA5E9),
  'cat_psychologist': Color(0xFF8B5CF6),
  'cat_journalist': Color(0xFF6366F1),
  'cat_actor': Color(0xFFEC4899),
  'cat_musician': Color(0xFFA855F7),
  'cat_animator': Color(0xFF14B8A6),
  'cat_event': Color(0xFFF43F5E),
  'cat_cleaning_pro': Color(0xFF475569),
  'cat_glazier': Color(0xFF38BDF8),
  'cat_tiler': Color(0xFFF59E0B),
  'cat_roofer': Color(0xFF92400E),
  'cat_carpenter': Color(0xFFB45309),
  'cat_locksmith': Color(0xFF374151),
  'cat_laundry': Color(0xFF7DD3FC),
  'cat_carwash': Color(0xFF3B82F6),
  'cat_tutor': Color(0xFF10B981),
  'cat_admin': Color(0xFF1D4ED8),
  'cat_logistics': Color(0xFF0F766E),
  'cat_call_center': Color(0xFF7C3AED),
  'cat_other': Color(0xFF9CA3AF),
};

/// Employment-type slugs (first item is "all").
const List<String> kEmploymentTypes = [
  'all',
  'emp_fulltime',
  'emp_parttime',
  'emp_onetime',
];

/// Employment type → icon mapping.
const Map<String, IconData> kEmpTypeIcons = {
  'all': Icons.list_alt_rounded,
  'emp_fulltime': Icons.work_rounded,
  'emp_parttime': Icons.work_history_rounded,
  'emp_onetime': Icons.flash_on_rounded,
};

/// Employment type → accent colour mapping.
const Map<String, Color> kEmpTypeColors = {
  'all': Color(0xFF2563EB),
  'emp_fulltime': Color(0xFF2563EB),
  'emp_parttime': Color(0xFF7C3AED),
  'emp_onetime': Color(0xFFF97316),
};
